### ISSUE TITLE
Add husky prepush hooks to run lints & tests

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#1]
Install husky into dependencies and run eslint and jest tests before push.

**Comment by darthgera123** [comment]
i like to take up this issue. Please guide me a little as to what exactly needs to be done

**Comment by bogas04** [comment]
Thank you so much @dart

**Comment by bogas04** [comment]
Thank you so much @darthgera123.

Basically we need to add a prepush script to our package.json making use of husky, and in that script we'll run `npm test`. You can read about husky on their [npm page](https://www.npmjs.com/package/husky). It's a very basic task.

**Comment by darthgera123** [comment]
its open right now? okay will do

**Comment by bogas04** [comment]
While at it, also include another script `lint` that'll run eslint on our JS files.

**Comment by darthgera123** [comment]
sure will do thanks for the help
