### ISSUE TITLE
Add Icon library of SVG icons

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#10]
SVG are ideal for glyphs as they can be inlined and load instantly. This isn't the case with font based icons that wait on fonts to load before showing anything to user. This gives poor experience on mobile where even if your content is loaded, the buttons might look empty or with X strange X marks everywhere.

Let's create `components/Icons/` dir that'll have React SVG components, which can then be used anywhere in the code base (buttons, titles, sidebars, sections etc).

You can find the icon of your choice from font awesome, get it's SVG code paste it in [svgr.now.sh](https://svgr.now.sh/), paste the React code in said directory and done. Thereafter we can add props like direction for chevron or color or size to fiddle with it.

You can refer to my project [here](https://github.com/KhalisFoundation/sttm-web/tree/dev/src/js/components/Icons).

Do note that if we use font awesome, we need to add credits in some page of our website. Probably legal page or footer. 

Some obvious icons

* Arrow 
* Chevron
* Save/Heart/Bookmark
* Share
* Search
* Wrench/Gears
* Human (for user account)
* Hamburger (for menu)
* Rupee

We can add rest as time passes. 

I guess we can load them all in our home page for demonstration purpose for now.

**Comment by twishasaraiya** [comment]
I would like to work on this issue.

**Comment by bogas04** [comment]
Fantastic. Please let me know if you need any help during the process :)

**Comment by darthgera123** [comment]
when can we work on the issues referenced here
