### ISSUE TITLE
Add <Footer /> 

### ISSUE THREAD

**Issue by sambhav2612** [GirlScriptSummerOfCode/Upay#17]
A small and descriptive footer can be added to the present functionality set.

**Comment by roygrv21** [comment]
I would like to work on this issue

**Comment by roygrv21** [comment]
@bogas04 Can I get assign to this?

**Comment by bogas04** [comment]
On mobile. You can begin  working on this.

**Comment by roygrv21** [comment]
Okay @bogas04
