### ISSUE TITLE
Use cross-env to support Windows for development

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#22]
We are using bash variables here in our scripts, which isn't supported in DOS environment.

In order to support windows, we can use [cross-env](https://www.npmjs.com/package/cross-env) (add to devDependencies using `npm i -D cross-env`) and simply prepend cross-env in our scripts;

```diff
-    "test": "NODE_ENV=test jest && npm run lint",
+    "test": "cross-env NODE_ENV=test jest && npm run lint",
```

```diff
-    "start": "NODE_ENV=production node server"
+    "start": "cross-env NODE_ENV=production node server"
  },
```

**Comment by Nshul** [comment]
can i work on this?

**Comment by bogas04** [comment]
Sorry @Nshul, I think @twishasaraiya has claimed it on Slack. Since she was the one who reported it, I'm giving it to her, I hope it's okay? Sorry!

**Comment by twishasaraiya** [comment]
I will be making the PR soon on this @bogas04

**Comment by Nshul** [comment]
@bogas04 thats cool.
