### ISSUE TITLE
Add CI to run our tests

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#25]
CircleCI/Travis either would do.

**Comment by devshiva619** [comment]
I am working on this 🙂

**Comment by bogas04** [comment]
Are you able to assign the issue to yourself? @devshiva619

**Comment by devshiva619** [comment]
I don't think I can assign it to myself. I have accepted the invitation so now you will be able to assign it to me

**Comment by devshiva619** [comment]
hey I think you fogot to label it as topcoder.

**Comment by devshiva619** [comment]
@bogas04 hey I have made PR for this plz have a look.
