### ISSUE TITLE
Improve <Items />

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#38]
It would render an array of items, each with 

* an image
* description
* Add button #12
* save for later button #13 

Feel free to take inspiration from sites like myntra/flipkart etc for design.
It should be a responsive grid that scales from desktop to mobile resolutions.

**Comment by SakshiShreya** [comment]
I will take this issue

**Comment by twishasaraiya** [comment]
I would like to work on it if possible

**Comment by bogas04** [comment]
dibs on @SakshiShreya so she's gonna work on this.
