### ISSUE TITLE
Add product page

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#41]
So once we have #38, it might link to a product page with more details of product, this is what we are talking about in this issue.

This would have product details in depth. Two people can work on this (updating API at server and creating UI in frontend)

**Comment by twishasaraiya** [comment]
I would like to work on UI once #38 is done.

**Comment by Nshul** [comment]
I would like to work at server end after #38

**Comment by bogas04** [comment]
Done

**Comment by bogas04** [comment]
Any update? @Nshul @twishasaraiya

**Comment by twishasaraiya** [comment]
@dj I am working on it. I have a few doubts(regarding routing) I will put them on the slack channel

**Comment by Nshul** [comment]
@bogas04, i am also working on it. Also, @twishasaraiya , his slack handle is not same as github handle. You have accidentally pinged wrong guy xD.
