### ISSUE TITLE
Setup react-styleguidist for component library

### ISSUE THREAD

**Issue by bogas04** [GirlScriptSummerOfCode/Upay#9]
[React styleguidist](https://react-styleguidist.js.org/) is a fun way of documenting your components. 

It makes use of markdown files placed in your component folder and reads jsx code blocks within it to create working examples. Even if we don't use the design guide server, the file itself acts as a good documentation about how to use your component, its props, etc. 

[this](https://github.com/zeit/next.js/issues/1641#issuecomment-323566682) might help with the configuration.

**Comment by bogas04** [comment]
@adarshlilha awesome. Go ahead and let me know if there's anything you need help with :D

**Comment by adarshlilha** [comment]
@bogas04 currently this project doesn't has webpack. Assuming we will be using it, shall I install webpack and then configure react styleguidist?

**Comment by bogas04** [comment]
@adarshlilha we do have webpack, just that it's being handled by Next.js. Check the link I shared in original comment.

https://github.com/zeit/next.js/issues/1641#issuecomment-323566682
